using CodeSentry.API.Models;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace CodeSentry.API.Services;

public interface IPdfReportService
{
    byte[] Generate(ScanState scanState);
}

public class PdfReportService : IPdfReportService
{
    // ── Color Palette ──
    private static readonly string BgDark = "#080A0F";
    private static readonly string BgCard = "#111827";
    private static readonly string AccentBlue = "#3B82F6";
    private static readonly string AccentRed = "#EF4444";
    private static readonly string AccentOrange = "#F59E0B";
    private static readonly string AccentTeal = "#10B981";
    private static readonly string TextPrimary = "#F9FAFB";
    private static readonly string TextSecondary = "#9CA3AF";
    private static readonly string BorderColor = "#1F2937";

    public byte[] Generate(ScanState scanState)
    {
        var result = scanState.Result!;
        var issues = result.Issues ?? new List<CodeIssue>();

        int critCount = issues.Count(i => i.Severity == "Critical");
        int warnCount = issues.Count(i => i.Severity == "Warning");
        int infoCount = issues.Count(i => i.Severity == "Info");
        int totalIssues = issues.Count;
        double debtHours = (critCount * 4.0) + (warnCount * 1.5) + (infoCount * 0.5);

        var fileGroups = issues
            .Where(i => !string.IsNullOrEmpty(i.FilePath))
            .GroupBy(i => i.FilePath)
            .OrderByDescending(g => g.Count())
            .ToList();

        var document = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(0);
                page.DefaultTextStyle(x => x.FontFamily("Arial"));
                page.Content().Background(BgDark).Padding(40).Column(col =>
                {
                    // ── COVER PAGE ──
                    col.Item().PaddingTop(30).Row(row =>
                    {
                        row.AutoItem().Text("◆").FontSize(32).FontColor(AccentBlue).Bold();
                        row.AutoItem().PaddingLeft(8).Text("CODESENTRY AI").FontSize(32).FontColor(AccentBlue).Bold();
                    });

                    col.Item().PaddingTop(30).Text("CODE SECURITY &").FontSize(36).FontColor(TextPrimary).Bold();
                    col.Item().Text("QUALITY REPORT").FontSize(36).FontColor(TextPrimary).Bold();

                    // Health Score Bar — 12px tall
                    col.Item().PaddingTop(24).Row(row =>
                    {
                        row.RelativeItem(7).Height(12).Background(BorderColor).AlignLeft()
                            .Width(Math.Max((float)(result.Score / 100.0) * 350, 4)).Height(12)
                            .Background(GetScoreColor(result.Score));
                        row.AutoItem().PaddingLeft(12).AlignMiddle()
                            .Text($"{result.Score}/100").FontSize(20).FontColor(GetScoreColor(result.Score)).Bold();
                    });
                    col.Item().PaddingTop(4).Text("HEALTH INDEX").FontSize(11).FontColor(TextSecondary).LetterSpacing(0.15f);

                    // Metadata
                    col.Item().PaddingTop(24).Column(meta =>
                    {
                        meta.Item().Text($"Scan ID: {result.Id}").FontSize(12).FontColor(TextSecondary);
                        meta.Item().PaddingTop(6).Text($"Scan Date: {scanState.CreatedAt:MMMM dd, yyyy}").FontSize(12).FontColor(TextSecondary);
                        meta.Item().PaddingTop(6).Text("Engine: CodeSentry Engine v2.0").FontSize(12).FontColor(TextSecondary);
                    });

                    // Summary Cards
                    col.Item().PaddingTop(24).Row(row =>
                    {
                        SummaryCard(row, "ISSUES", totalIssues.ToString(), AccentOrange);
                        SummaryCard(row, "CRITICAL", critCount.ToString(), AccentRed);
                        SummaryCard(row, "DEBT", $"{debtHours:F0}h", AccentBlue);
                    });

                    // Separator line before confidential text
                    col.Item().PaddingTop(30).LineHorizontal(1).LineColor(BorderColor);
                    col.Item().PaddingTop(8).Text("CONFIDENTIAL — Generated by CodeSentry AI Platform")
                        .FontSize(10).FontColor(TextSecondary);
                });
            });

            // ── PAGE 2: EXECUTIVE SUMMARY ──
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(0);
                page.DefaultTextStyle(x => x.FontFamily("Arial"));
                page.Header().Element(h => PageHeader(h, result.Id));
                page.Footer().Element(f => PageFooter(f, result.Id));
                page.Content().Background(BgDark).PaddingHorizontal(40).PaddingVertical(20).Column(col =>
                {
                    SectionHeader(col, "EXECUTIVE SUMMARY");

                    // AI Summary
                    var summaryParts = new List<string>();
                    summaryParts.Add($"{totalIssues} issues found across the repository.");
                    if (critCount > 0)
                    {
                        var topCrit = issues.FirstOrDefault(i => i.Severity == "Critical");
                        if (topCrit != null)
                            summaryParts.Add($"{critCount} critical: {topCrit.Title} in {topCrit.FilePath} requires immediate action.");
                    }
                    if (warnCount > 0) summaryParts.Add($"{warnCount} warnings detected.");
                    summaryParts.Add($"Health score: {result.Score}/100. Estimated {debtHours:F0}h of technical debt.");

                    col.Item().PaddingTop(10).Background(BgCard).Padding(16)
                        .Text(string.Join(" ", summaryParts)).FontSize(11).FontColor(TextPrimary).LineHeight(1.6f);

                    // Severity Breakdown
                    col.Item().PaddingTop(20).Text("SEVERITY BREAKDOWN").FontSize(12).FontColor(AccentBlue).Bold().LetterSpacing(0.1f);
                    col.Item().PaddingTop(8).Column(sev =>
                    {
                        SeverityRow(sev, "CRITICAL", critCount, totalIssues, AccentRed);
                        SeverityRow(sev, "WARNING", warnCount, totalIssues, AccentOrange);
                        SeverityRow(sev, "INFO", infoCount, totalIssues, AccentBlue);
                    });

                    // Top Affected Files
                    if (fileGroups.Count > 0)
                    {
                        col.Item().PaddingTop(20).Text("TOP AFFECTED FILES").FontSize(12).FontColor(AccentBlue).Bold().LetterSpacing(0.1f);
                        col.Item().PaddingTop(8).Table(table =>
                        {
                            table.ColumnsDefinition(c =>
                            {
                                c.RelativeColumn(5);
                                c.RelativeColumn(1);
                                c.RelativeColumn(1);
                            });
                            table.Header(h =>
                            {
                                h.Cell().Background(BgCard).Padding(6).Text("File Path").FontSize(9).FontColor(TextSecondary).Bold();
                                h.Cell().Background(BgCard).Padding(6).Text("Issues").FontSize(9).FontColor(TextSecondary).Bold();
                                h.Cell().Background(BgCard).Padding(6).Text("Risk %").FontSize(9).FontColor(TextSecondary).Bold();
                            });
                            foreach (var fg in fileGroups.Take(5))
                            {
                                int pct = totalIssues > 0 ? (int)Math.Round((double)fg.Count() / totalIssues * 100) : 0;
                                table.Cell().BorderBottom(1).BorderColor(BorderColor).Padding(6)
                                    .Text(fg.Key).FontSize(9).FontColor(TextPrimary);
                                table.Cell().BorderBottom(1).BorderColor(BorderColor).Padding(6)
                                    .Text(fg.Count().ToString()).FontSize(9).FontColor(TextPrimary);
                                table.Cell().BorderBottom(1).BorderColor(BorderColor).Padding(6)
                                    .Text($"{pct}%").FontSize(9).FontColor(AccentOrange);
                            }
                        });
                    }

                    // Scan Metadata
                    col.Item().PaddingTop(20).Text("SCAN METADATA").FontSize(12).FontColor(AccentBlue).Bold().LetterSpacing(0.1f);
                    col.Item().PaddingTop(8).Background(BgCard).Padding(12).Row(row =>
                    {
                        MetaCell(row, "Duration", result.Duration ?? "—");
                        MetaCell(row, "Files Scanned", fileGroups.Count.ToString());
                        MetaCell(row, "Engine", "v2.0");
                        MetaCell(row, "Scan ID", result.Id);
                    });
                });
            });

            // ── SECURITY ISSUES PAGES ──
            var securityIssues = issues.Where(i => i.Category == "Security").OrderByDescending(i => i.Severity == "Critical").ToList();
            if (securityIssues.Count > 0)
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.Margin(0);
                    page.DefaultTextStyle(x => x.FontFamily("Arial"));
                    page.Header().Element(h => PageHeader(h, result.Id));
                    page.Footer().Element(f => PageFooter(f, result.Id));
                    page.Content().Background(BgDark).PaddingHorizontal(40).PaddingVertical(20).Column(col =>
                    {
                        SectionHeader(col, "SECURITY VULNERABILITIES");
                        col.Item().PaddingBottom(10)
                            .Text($"{securityIssues.Count(i => i.Severity == "Critical" || i.Severity == "Warning")} critical and warning security issues detected")
                            .FontSize(11).FontColor(TextSecondary);

                        foreach (var issue in securityIssues)
                        {
                            col.Item().PaddingBottom(8).Element(e => IssueCard(e, issue));
                        }
                    });
                });
            }

            // ── CODE QUALITY PAGES ──
            var qualityIssues = issues.Where(i => i.Category == "Quality" || i.Category == "Performance").ToList();
            if (qualityIssues.Count > 0)
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.Margin(0);
                    page.DefaultTextStyle(x => x.FontFamily("Arial"));
                    page.Header().Element(h => PageHeader(h, result.Id));
                    page.Footer().Element(f => PageFooter(f, result.Id));
                    page.Content().Background(BgDark).PaddingHorizontal(40).PaddingVertical(20).Column(col =>
                    {
                        SectionHeader(col, "CODE QUALITY & TECH DEBT");
                        col.Item().PaddingBottom(10)
                            .Text($"Estimated {debtHours:F0} hours of technical debt")
                            .FontSize(11).FontColor(TextSecondary);

                        foreach (var issue in qualityIssues)
                        {
                            col.Item().PaddingBottom(8).Element(e => IssueCard(e, issue));
                        }
                    });
                });
            }

            // ── AI SUGGESTIONS PAGE ──
            var suggestions = issues.Where(i => !string.IsNullOrEmpty(i.Suggestion)).OrderByDescending(i => i.Severity == "Critical").Take(10).ToList();
            if (suggestions.Count > 0)
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.Margin(0);
                    page.DefaultTextStyle(x => x.FontFamily("Arial"));
                    page.Header().Element(h => PageHeader(h, result.Id));
                    page.Footer().Element(f => PageFooter(f, result.Id));
                    page.Content().Background(BgDark).PaddingHorizontal(40).PaddingVertical(20).Column(col =>
                    {
                        SectionHeader(col, "AI-POWERED FIX SUGGESTIONS");
                        col.Item().PaddingBottom(10)
                            .Text("Top highest-impact fixes")
                            .FontSize(10).FontColor(TextSecondary);

                        foreach (var issue in suggestions)
                        {
                            col.Item().PaddingBottom(8).Background(BgCard).Border(1).BorderColor(BorderColor).Padding(12).Column(card =>
                            {
                                card.Item().Row(r =>
                                {
                                    r.AutoItem().Element(e => SeverityBadge(e, issue.Severity));
                                    r.AutoItem().PaddingLeft(8).AlignMiddle()
                                        .Text(issue.Title).FontSize(11).FontColor(TextPrimary).Bold();
                                });
                                card.Item().PaddingTop(4).Text($"{issue.FilePath} : line {issue.LineNumber}")
                                    .FontSize(9).FontColor(TextSecondary).FontFamily("Courier");
                                if (!string.IsNullOrEmpty(issue.Suggestion))
                                {
                                    card.Item().PaddingTop(6).Background("#0D1117").Padding(8)
                                        .Text(issue.Suggestion).FontSize(8).FontColor("#E6EDF3").FontFamily("Courier").LineHeight(1.4f);
                                }
                                card.Item().PaddingTop(6).Row(r =>
                                {
                                    r.AutoItem().Element(e => EffortBadge(e, issue.EffortLevel));
                                    r.AutoItem().PaddingLeft(8).AlignMiddle()
                                        .Text($"~{EstimateTime(issue.Severity)} to fix").FontSize(8).FontColor(TextSecondary);
                                });
                            });
                        }
                    });
                });
            }

            // ── FILES ANALYSIS PAGE ──
            if (fileGroups.Count > 0)
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.Margin(0);
                    page.DefaultTextStyle(x => x.FontFamily("Arial"));
                    page.Header().Element(h => PageHeader(h, result.Id));
                    page.Footer().Element(f => PageFooter(f, result.Id));
                    page.Content().Background(BgDark).PaddingHorizontal(40).PaddingVertical(20).Column(col =>
                    {
                        SectionHeader(col, "FILES ANALYSIS");

                        col.Item().PaddingTop(8).Table(table =>
                        {
                            table.ColumnsDefinition(c =>
                            {
                                c.RelativeColumn(5);
                                c.RelativeColumn(1);
                                c.RelativeColumn(1);
                            });
                            table.Header(h =>
                            {
                                h.Cell().Background(AccentBlue).Padding(6).Text("File Path").FontSize(9).FontColor(TextPrimary).Bold();
                                h.Cell().Background(AccentBlue).Padding(6).Text("Issues").FontSize(9).FontColor(TextPrimary).Bold();
                                h.Cell().Background(AccentBlue).Padding(6).Text("Risk %").FontSize(9).FontColor(TextPrimary).Bold();
                            });
                            foreach (var fg in fileGroups)
                            {
                                int pct = totalIssues > 0 ? (int)Math.Round((double)fg.Count() / totalIssues * 100) : 0;
                                var bgRow = fileGroups.IndexOf(fg) % 2 == 0 ? BgCard : BgDark;
                                table.Cell().Background(bgRow).Padding(6).Text(fg.Key).FontSize(8).FontColor(TextPrimary);
                                table.Cell().Background(bgRow).Padding(6).Text(fg.Count().ToString()).FontSize(8).FontColor(TextPrimary);
                                table.Cell().Background(bgRow).Padding(6).Text($"{pct}%").FontSize(8).FontColor(pct > 20 ? AccentRed : AccentOrange);
                            }
                        });
                    });
                });
            }

            // ── LAST PAGE: ABOUT ──
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(0);
                page.DefaultTextStyle(x => x.FontFamily("Arial"));
                page.Content().Background(BgDark).Padding(40).Column(col =>
                {
                    col.Item().PaddingTop(80).Row(row =>
                    {
                        row.AutoItem().Text("◆").FontSize(28).FontColor(AccentBlue).Bold();
                        row.AutoItem().PaddingLeft(8).Text("CODESENTRY AI").FontSize(28).FontColor(AccentBlue).Bold();
                    });

                    col.Item().PaddingTop(30).Text("This report was generated by CodeSentry AI Static Analysis Engine v2.0")
                        .FontSize(12).FontColor(TextPrimary).LineHeight(1.6f);

                    col.Item().PaddingTop(20).Text("Analysis performed using:").FontSize(11).FontColor(TextSecondary);
                    col.Item().PaddingTop(8).Column(list =>
                    {
                        foreach (var tool in new[] {
                            "Security Vulnerability Scanner",
                            "Code Quality Analyzer",
                            "Dependency CVE Checker",
                            "Git History Scanner",
                            "Cross-File Data Flow Tracker",
                            "API Surface Mapper"
                        })
                        {
                            list.Item().PaddingTop(4).Text($"•  {tool}").FontSize(10).FontColor(TextPrimary);
                        }
                    });

                    col.Item().PaddingTop(40).Text("For questions contact:").FontSize(10).FontColor(TextSecondary);
                    col.Item().PaddingTop(4).Text("support@codesentry.ai").FontSize(10).FontColor(AccentBlue);

                    col.Item().PaddingTop(40).Text($"© {DateTime.UtcNow.Year} CodeSentry AI").FontSize(9).FontColor(TextSecondary);
                });
            });
        });

        return document.GeneratePdf();
    }

    // ── Helper Methods ──

    private void PageHeader(IContainer container, string scanId)
    {
        container.Background(BgDark).PaddingHorizontal(40).PaddingTop(12).Column(col =>
        {
            col.Item().Row(row =>
            {
                row.AutoItem().Text("◆ CODESENTRY AI").FontSize(9).FontColor(AccentBlue).Bold();
                row.RelativeItem().AlignRight().Text(text =>
                {
                    text.CurrentPageNumber().FontSize(9).FontColor(TextSecondary);
                    text.Span(" / ").FontSize(9).FontColor(TextSecondary);
                    text.TotalPages().FontSize(9).FontColor(TextSecondary);
                });
            });
            col.Item().PaddingTop(4).LineHorizontal(2).LineColor(AccentBlue);
        });
    }

    private void PageFooter(IContainer container, string scanId)
    {
        container.Background(BgDark).PaddingHorizontal(40).PaddingBottom(12).Column(col =>
        {
            col.Item().LineHorizontal(1).LineColor(TextSecondary);
            col.Item().PaddingTop(6).Row(row =>
            {
                row.RelativeItem().AlignCenter().Text("CONFIDENTIAL").FontSize(8).FontColor(TextSecondary).LetterSpacing(0.2f);
                row.AutoItem().Text(scanId).FontSize(8).FontColor(TextSecondary);
            });
        });
    }

    private void SectionHeader(ColumnDescriptor col, string title)
    {
        col.Item().PaddingTop(24).PaddingBottom(8).Column(inner =>
        {
            inner.Item().Text(title).FontSize(18).FontColor(AccentBlue).Bold().LetterSpacing(0.1f);
            inner.Item().PaddingTop(6).LineHorizontal(1).LineColor(BorderColor);
        });
    }

    private void SummaryCard(RowDescriptor row, string label, string value, string color)
    {
        row.RelativeItem().Background(BgCard).Border(1).BorderColor(BorderColor).Padding(16).Column(col =>
        {
            col.Item().Text(label).FontSize(10).FontColor(TextSecondary).LetterSpacing(0.15f);
            col.Item().PaddingTop(6).Text(value).FontSize(28).FontColor(color).Bold();
        });
    }

    private void SeverityRow(ColumnDescriptor col, string label, int count, int total, string color)
    {
        int pct = total > 0 ? (int)Math.Round((double)count / total * 100) : 0;
        col.Item().PaddingTop(4).Background(BgCard).Padding(10).Row(row =>
        {
            row.ConstantItem(75).AlignMiddle().Text(label).FontSize(10).FontColor(color).Bold();
            row.RelativeItem(4).AlignMiddle().Height(10).Background(BorderColor).AlignLeft()
                .Width(Math.Max(pct, 2) * 2f).Height(10).Background(color);
            row.ConstantItem(40).AlignRight().AlignMiddle().Text(count.ToString()).FontSize(11).FontColor(color).Bold();
            row.ConstantItem(55).AlignRight().AlignMiddle().Text($"({pct}%)").FontSize(10).FontColor(TextSecondary);
        });
    }

    private void MetaCell(RowDescriptor row, string label, string value)
    {
        row.RelativeItem().Column(col =>
        {
            col.Item().Text(label).FontSize(8).FontColor(TextSecondary);
            col.Item().PaddingTop(2).Text(value).FontSize(10).FontColor(TextPrimary).Bold();
        });
    }

    private void IssueCard(IContainer container, CodeIssue issue)
    {
        // Truncate long file paths
        var displayPath = issue.FilePath.Length > 60
            ? "..." + issue.FilePath[^57..]
            : issue.FilePath;

        container.Background(BgCard).Border(1).BorderColor(BorderColor).Padding(16).Column(card =>
        {
            card.Item().Row(r =>
            {
                r.AutoItem().Element(e => SeverityBadge(e, issue.Severity));
                r.AutoItem().PaddingLeft(10).AlignMiddle()
                    .Text(issue.Title).FontSize(12).FontColor(TextPrimary).Bold();
            });
            card.Item().PaddingTop(6)
                .Text($"{displayPath} : line {issue.LineNumber}")
                .FontSize(8).FontColor(TextSecondary).FontFamily("Courier");

            if (!string.IsNullOrEmpty(issue.Description))
            {
                card.Item().PaddingTop(8).Text(text =>
                {
                    text.Span("Description: ").FontSize(11).FontColor(TextSecondary).Bold();
                    text.Span(issue.Description).FontSize(11).FontColor(TextPrimary).LineHeight(1.4f);
                });
            }

            if (!string.IsNullOrEmpty(issue.Suggestion))
            {
                card.Item().PaddingTop(8).Text("Suggested Fix:").FontSize(11).FontColor(TextSecondary).Bold();
                card.Item().PaddingTop(4).Background("#0D1117").Padding(10)
                    .Text(issue.Suggestion).FontSize(9).FontColor("#E6EDF3").FontFamily("Courier").LineHeight(1.4f);
            }

            // Confidence bar — 8px tall with visible percentage
            card.Item().PaddingTop(8).Row(r =>
            {
                r.ConstantItem(68).AlignMiddle().Text("Confidence:").FontSize(9).FontColor(TextSecondary);
                r.RelativeItem(3).AlignMiddle().Height(8).Background(BorderColor).AlignLeft()
                    .Width(Math.Max(issue.ConfidenceScore, 2) * 1.2f).Height(8)
                    .Background(issue.ConfidenceScore >= 80 ? AccentTeal : issue.ConfidenceScore >= 50 ? AccentOrange : TextSecondary);
                r.ConstantItem(45).AlignRight().AlignMiddle()
                    .Text($"{issue.ConfidenceScore}%").FontSize(9).FontColor(
                        issue.ConfidenceScore >= 80 ? AccentTeal : issue.ConfidenceScore >= 50 ? AccentOrange : TextSecondary).Bold();
            });
        });
    }

    private void SeverityBadge(IContainer container, string severity)
    {
        var (bg, fg) = severity switch
        {
            "Critical" => (AccentRed, "#FFFFFF"),
            "Warning" => (AccentOrange, "#1F2937"),
            _ => (AccentBlue, "#FFFFFF")
        };
        container.Background(bg).PaddingVertical(4).PaddingHorizontal(10)
            .Text(severity.ToUpperInvariant()).FontSize(9).FontColor(fg).Bold();
    }

    private void EffortBadge(IContainer container, string effort)
    {
        var bg = effort switch
        {
            "Easy" => AccentTeal,
            "Hard" => AccentRed,
            _ => AccentOrange
        };
        container.Background(bg).PaddingVertical(4).PaddingHorizontal(10)
            .Text(string.IsNullOrEmpty(effort) ? "MEDIUM" : effort.ToUpperInvariant()).FontSize(9).FontColor("#FFFFFF").Bold();
    }

    private static string GetScoreColor(int score) =>
        score >= 80 ? "#10B981" : score >= 50 ? "#F59E0B" : "#EF4444";

    private static string EstimateTime(string severity) => severity switch
    {
        "Critical" => "2-4h",
        "Warning" => "30-90min",
        _ => "15-30min"
    };
}
