// <auto-generated />
using System;
using CodeSentry.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeSentry.API.Data.Migrations
{
    [DbContext(typeof(CodeSentryDbContext))]
    [Migration("20260523124423_AddIsActiveToLocalUser")]
    partial class AddIsActiveToLocalUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("CodeSentry.API.Models.ApiKey", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("KeyValue")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("KeyValue");

                    b.Property<DateTime?>("LastUsed")
                        .HasColumnType("TEXT")
                        .HasColumnName("LastUsed");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_ApiKeys_UserId");

                    b.ToTable("ApiKeys", (string)null);
                });

            modelBuilder.Entity("CodeSentry.API.Models.LocalUser", b =>
                {
                    b.Property<string>("SupabaseId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("SupabaseId");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("DisplayName");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("Email");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("IsActive");

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("IsAdmin");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("TEXT")
                        .HasColumnName("LastLogin");

                    b.Property<DateTime?>("PlanResetDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("PlanResetDate");

                    b.Property<string>("PlanType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("FREE")
                        .HasColumnName("PlanType");

                    b.Property<int>("ScansThisMonth")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("ScansThisMonth");

                    b.HasKey("SupabaseId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_LocalUsers_Email");

                    b.ToTable("LocalUsers", (string)null);
                });

            modelBuilder.Entity("CodeSentry.API.Models.ScanState", b =>
                {
                    b.Property<string>("ScanId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("ScanId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("EstimatedTime")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("EstimatedTime");

                    b.Property<int>("HealthScore")
                        .HasColumnType("INTEGER")
                        .HasColumnName("HealthScore");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .HasColumnName("Message");

                    b.Property<int>("ProgressPercent")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ProgressPercent");

                    b.Property<string>("RepoSize")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("RepoSize");

                    b.Property<string>("RepositoryName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("RepositoryName");

                    b.Property<string>("Result")
                        .HasColumnType("TEXT")
                        .HasColumnName("Result");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("Status");

                    b.Property<string>("UserId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("UserId");

                    b.HasKey("ScanId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_ScanStates_CreatedAt");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_ScanStates_Status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_ScanStates_UserId");

                    b.ToTable("ScanStates", (string)null);
                });

            modelBuilder.Entity("CodeSentry.API.Models.ApiKey", b =>
                {
                    b.HasOne("CodeSentry.API.Models.LocalUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
